#pragma once
#include <TCoreMacros.h>
TCORE_BEGIN_C_LINKAGE

TCORE_DEFINE_HANDLE(TGfxGpu);
TCORE_DEFINE_HANDLE(TGfxSwapchain);
TCORE_DEFINE_HANDLE(TGfxTexture);
TCORE_DEFINE_HANDLE(TGfxBuffer);
TCORE_DEFINE_HANDLE(TGfxSampler);
TCORE_DEFINE_HANDLE(TGfxShaderSource);
TCORE_DEFINE_HANDLE(TGfxBindingTable);
TCORE_DEFINE_HANDLE(TGfxCommandBuffer);
TCORE_DEFINE_HANDLE(TGfxCommandBundle);
TCORE_DEFINE_HANDLE(TGfxQueue);
TCORE_DEFINE_HANDLE(TGfxFence);
TCORE_DEFINE_HANDLE(TGfxHeap);
TCORE_DEFINE_HANDLE(TGfxPipeline);
TCORE_DEFINE_HANDLE(TGfxSubRasterpass);

typedef struct ITGfxRenderer ITGfxRenderer;
typedef struct ITGfxResourceManager ITGfxResourceManager;

typedef enum TGfxExtensionType
{
} TGfxExtensionType;

typedef struct TGfxExtension
{
	TGfxExtension* NextExtension;
	TGfxExtensionType CurrentExtensionType;
} TGfxExtension;

typedef enum TGfxColorSpace
{
	TGFX_COLORSPACE_sRGB_NONLINEAR,
	TGFX_COLORSPACE_EXTENDED_sRGB_LINEAR,
	TGFX_COLORSPACE_HDR10_ST2084
} TGfxColorSpace;

typedef enum TGfxTextureChannels
{
	TGFX_TEXTURE_CHANNELS_UNDEF,
	TGFX_TEXTURE_CHANNELS_BGRA8UB,	  // Unsigned but non-normalized char
	TGFX_TEXTURE_CHANNELS_BGRA8UNORM, // Unsigned and normalized char
	TGFX_TEXTURE_CHANNELS_BGRA8SRGB,

	TGFX_TEXTURE_CHANNELS_RGBA32F,
	TGFX_TEXTURE_CHANNELS_RGBA32UI,
	TGFX_TEXTURE_CHANNELS_RGBA32I,
	TGFX_TEXTURE_CHANNELS_RGBA8UB,
	TGFX_TEXTURE_CHANNELS_RGBA8UNORM,
	TGFX_TEXTURE_CHANNELS_RGBA8SRGB,
	TGFX_TEXTURE_CHANNELS_RGBA8B,
	TGFX_TEXTURE_CHANNELS_RGBA16F,

	TGFX_TEXTURE_CHANNELS_RGB32F,
	TGFX_TEXTURE_CHANNELS_RGB32UI,
	TGFX_TEXTURE_CHANNELS_RGB32I,
	TGFX_TEXTURE_CHANNELS_RGB8UB,
	TGFX_TEXTURE_CHANNELS_RGB8B,

	TGFX_TEXTURE_CHANNELS_RA32F,
	TGFX_TEXTURE_CHANNELS_RA32UI,
	TGFX_TEXTURE_CHANNELS_RA32I,
	TGFX_TEXTURE_CHANNELS_RA8UB,
	TGFX_TEXTURE_CHANNELS_RA8B,

	TGFX_TEXTURE_CHANNELS_R32F,
	TGFX_TEXTURE_CHANNELS_R32UI,
	TGFX_TEXTURE_CHANNELS_R32I,
	TGFX_TEXTURE_CHANNELS_R8UB,
	TGFX_TEXTURE_CHANNELS_R8B,

	TGFX_TEXTURE_CHANNELS_D32,
	TGFX_TEXTURE_CHANNELS_D24S8,
	TGFX_TEXTURE_CHANNELS_A2B10G10R10_UNORM,
	TGFX_TEXTURE_CHANNELS_UNDEF2
} TGfxTextureChannels;

typedef enum TGfxTextureComponentMask
{
	TGFX_TEXTURECOMPONENTMASK_R = 1,
	TGFX_TEXTURECOMPONENTMASK_G = 1 << 1,
	TGFX_TEXTURECOMPONENTMASK_B = 1 << 2,
	TGFX_TEXTURECOMPONENTMASK_A = 1 << 3,
	TGFX_TEXTURECOMPONENTMASK_RG = TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_G,
	TGFX_TEXTURECOMPONENTMASK_RB = TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_B,
	TGFX_TEXTURECOMPONENTMASK_RA = TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_GB = TGFX_TEXTURECOMPONENTMASK_G | TGFX_TEXTURECOMPONENTMASK_B,
	TGFX_TEXTURECOMPONENTMASK_GA = TGFX_TEXTURECOMPONENTMASK_G | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_BA = TGFX_TEXTURECOMPONENTMASK_B | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_RGB =
		TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_G | TGFX_TEXTURECOMPONENTMASK_B,
	TGFX_TEXTURECOMPONENTMASK_RGA =
		TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_G | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_RBA =
		TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_B | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_GBA =
		TGFX_TEXTURECOMPONENTMASK_G | TGFX_TEXTURECOMPONENTMASK_B | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_RGBA = TGFX_TEXTURECOMPONENTMASK_R | TGFX_TEXTURECOMPONENTMASK_G |
									 TGFX_TEXTURECOMPONENTMASK_B | TGFX_TEXTURECOMPONENTMASK_A,
	TGFX_TEXTURECOMPONENTMASK_ALL, // All possible values if texture's format is known
	TGFX_TEXTURECOMPONENTMASK_NONE
} TGfxTextureComponentMask;

typedef enum TGfxWindowPresentation
{
	TGFX_WINDOWPRESENTATION_FIFO,
	TGFX_WINDOWPRESENTATION_FIFO_RELAXED,
	TGFX_WINDOWPRESENTATION_IMMEDIATE,
	TGFX_WINDOWPRESENTATION_MAILBOX
} TGfxWindowPresentation;

typedef enum TGfxMemoryAllocationType
{
	TGFX_MEMORYALLOCATIONTYPE_DEVICELOCAL = 0,
	TGFX_MEMORYALLOCATIONTYPE_HOSTVISIBLE = 1,
	TGFX_MEMORYALLOCATIONTYPE_FASTHOSTVISIBLE = 2,
	TGFX_MEMORYALLOCATIONTYPE_READBACK = 3
} TGfxMemoryAllocationType;

// Don't forget that TGFX stores how you access them in shaders
// So backend'll probably cull some unnecessary transitions
typedef enum TGfxImageAccess
{
	TGFX_IMAGE_ACCESS_NO_ACCESS,
	TGFX_IMAGE_ACCESS_RTCOLOR_READONLY,
	TGFX_IMAGE_ACCESS_RTCOLOR_WRITEONLY,
	TGFX_IMAGE_ACCESS_RTCOLOR_READWRITE,
	TGFX_IMAGE_ACCESS_SWAPCHAIN_DISPLAY,
	TGFX_IMAGE_ACCESS_TRANSFER_DIST,
	TGFX_IMAGE_ACCESS_TRANSFER_SRC,
	TGFX_IMAGE_ACCESS_SHADER_SAMPLEONLY,
	TGFX_IMAGE_ACCESS_SHADER_WRITEONLY,
	TGFX_IMAGE_ACCESS_SHADER_SAMPLEWRITE,
	TGFX_IMAGE_ACCESS_DEPTHSTENCIL_READONLY,
	TGFX_IMAGE_ACCESS_DEPTHSTENCIL_WRITEONLY,
	TGFX_IMAGE_ACCESS_DEPTHSTENCIL_READWRITE,
	TGFX_IMAGE_ACCESS_DEPTH_READONLY,
	TGFX_IMAGE_ACCESS_DEPTH_WRITEONLY,
	TGFX_IMAGE_ACCESS_DEPTH_READWRITE,
	TGFX_IMAGE_ACCESS_DEPTHREAD_STENCILREADWRITE,
	TGFX_IMAGE_ACCESS_DEPTHREAD_STENCILWRITE,
	TGFX_IMAGE_ACCESS_DEPTHWRITE_STENCILREAD,
	TGFX_IMAGE_ACCESS_DEPTHWRITE_STENCILREADWRITE,
	TGFX_IMAGE_ACCESS_DEPTHREADWRITE_STENCILREAD,
	TGFX_IMAGE_ACCESS_DEPTHREADWRITE_STENCILWRITE
} TGfxImageAccess;

typedef enum TGfxTextureDimensions
{
	TGFX_TEXTURE_DIMENSIONS_2D = 0,
	TGFX_TEXTURE_DIMENSIONS_3D = 1,
	TGFX_TEXTURE_DIMENSIONS_2DCUBE = 2
} TGfxTextureDimensions;

typedef enum TGfxDataType
{
	TGFX_DATATYPE_UNDEFINED = 0,
	TGFX_DATATYPE_I8 = 1,
	TGFX_DATATYPE_I16 = 2,
	TGFX_DATATYPE_I32 = 3,
	TGFX_DATATYPE_U8 = 4,
	TGFX_DATATYPE_U16 = 5,
	TGFX_DATATYPE_U32 = 6,
	TGFX_DATATYPE_F32 = 7,
	TGFX_DATATYPE_FVEC2,
	TGFX_DATATYPE_FVEC3,
	TGFX_DATATYPE_FVEC4,
	TGFX_DATATYPE_FMAT4x4
} TGfxDataType;

typedef enum TGfxPipelineType
{
	TGFX_PIPELINETYPE_RASTER = 0,
	TGFX_PIPELINETYPE_COMPUTE = 1,
	TGFX_PIPELINETYPE_RAYTRACING = 2
} TGfxPipelineType;

inline TGfxDataType TGfxGetDataTypeFromChannels(TGfxTextureChannels format)
{
	switch (format)
	{
	// 32-bit float formats
	case TGFX_TEXTURE_CHANNELS_D32:
	case TGFX_TEXTURE_CHANNELS_RGBA32F:
	case TGFX_TEXTURE_CHANNELS_RA32F:
	case TGFX_TEXTURE_CHANNELS_RGB32F: return TGFX_DATATYPE_F32;

	// 32-bit unsigned integer formats
	case TGFX_TEXTURE_CHANNELS_RGBA32UI:
	case TGFX_TEXTURE_CHANNELS_RGB32UI:
	case TGFX_TEXTURE_CHANNELS_RA32UI:
	case TGFX_TEXTURE_CHANNELS_R32UI: return TGFX_DATATYPE_U32;

	// 32-bit signed integer formats
	case TGFX_TEXTURE_CHANNELS_RGBA32I:
	case TGFX_TEXTURE_CHANNELS_RGB32I:
	case TGFX_TEXTURE_CHANNELS_R32I: return TGFX_DATATYPE_I32;

	// 8-bit unsigned (normalized or not) and other 8-bit variants map to U8
	case TGFX_TEXTURE_CHANNELS_BGRA8UB:
	case TGFX_TEXTURE_CHANNELS_BGRA8UNORM:
	case TGFX_TEXTURE_CHANNELS_BGRA8SRGB:
	case TGFX_TEXTURE_CHANNELS_RGBA8UB:
	case TGFX_TEXTURE_CHANNELS_RGBA8UNORM:
	case TGFX_TEXTURE_CHANNELS_RGBA8SRGB:
	case TGFX_TEXTURE_CHANNELS_RGBA8B:
	case TGFX_TEXTURE_CHANNELS_RGB8UB:
	case TGFX_TEXTURE_CHANNELS_RGB8B:
	case TGFX_TEXTURE_CHANNELS_RA8UB:
	case TGFX_TEXTURE_CHANNELS_RA8B:
	case TGFX_TEXTURE_CHANNELS_R8UB:
	case TGFX_TEXTURE_CHANNELS_R8B: return TGFX_DATATYPE_U8;

	// Fallback for unknown / unsupported formats
	default: return TGFX_DATATYPE_UNDEFINED;
	}
}

inline TGfxTextureComponentMask TGfxGetColorComponents(TGfxTextureChannels chnnls)
{
	switch (chnnls)
	{
	case TGFX_TEXTURE_CHANNELS_BGRA8UB:
	case TGFX_TEXTURE_CHANNELS_BGRA8UNORM:
	case TGFX_TEXTURE_CHANNELS_RGBA32F:
	case TGFX_TEXTURE_CHANNELS_RGBA32UI:
	case TGFX_TEXTURE_CHANNELS_RGBA32I:
	case TGFX_TEXTURE_CHANNELS_RGBA8UB:
	case TGFX_TEXTURE_CHANNELS_RGBA8B: return TGFX_TEXTURECOMPONENTMASK_RGBA;
	case TGFX_TEXTURE_CHANNELS_RGB32F:
	case TGFX_TEXTURE_CHANNELS_RGB32UI:
	case TGFX_TEXTURE_CHANNELS_RGB32I:
	case TGFX_TEXTURE_CHANNELS_RGB8UB:
	case TGFX_TEXTURE_CHANNELS_RGB8B: return TGFX_TEXTURECOMPONENTMASK_RGB;
	case TGFX_TEXTURE_CHANNELS_RA32F:
	case TGFX_TEXTURE_CHANNELS_RA32UI:
	case TGFX_TEXTURE_CHANNELS_RA32I:
	case TGFX_TEXTURE_CHANNELS_RA8UB:
	case TGFX_TEXTURE_CHANNELS_RA8B: return TGFX_TEXTURECOMPONENTMASK_RA;
	case TGFX_TEXTURE_CHANNELS_R32F:
	case TGFX_TEXTURE_CHANNELS_R32UI:
	case TGFX_TEXTURE_CHANNELS_R32I:
	case TGFX_TEXTURE_CHANNELS_R8UB:
	case TGFX_TEXTURE_CHANNELS_R8B: return TGFX_TEXTURECOMPONENTMASK_R;
	case TGFX_TEXTURE_CHANNELS_D32:
	case TGFX_TEXTURE_CHANNELS_D24S8:
	default: return TGFX_TEXTURECOMPONENTMASK_NONE;
	}
}

inline unsigned char TGfxGetSizeOfPixel(TGfxTextureChannels channeltype)
{
	switch (channeltype)
	{
	case TGFX_TEXTURE_CHANNELS_R8B:
	case TGFX_TEXTURE_CHANNELS_R8UB: return 1;
	case TGFX_TEXTURE_CHANNELS_RGB8B:
	case TGFX_TEXTURE_CHANNELS_RGB8UB: return 3;
	case TGFX_TEXTURE_CHANNELS_D24S8:
	case TGFX_TEXTURE_CHANNELS_D32:
	case TGFX_TEXTURE_CHANNELS_RGBA8B:
	case TGFX_TEXTURE_CHANNELS_RGBA8UB:
	case TGFX_TEXTURE_CHANNELS_BGRA8UB:
	case TGFX_TEXTURE_CHANNELS_BGRA8UNORM:
	case TGFX_TEXTURE_CHANNELS_R32F:
	case TGFX_TEXTURE_CHANNELS_R32I:
	case TGFX_TEXTURE_CHANNELS_R32UI: return 4;
	case TGFX_TEXTURE_CHANNELS_RA32F:
	case TGFX_TEXTURE_CHANNELS_RA32I:
	case TGFX_TEXTURE_CHANNELS_RA32UI: return 8;
	case TGFX_TEXTURE_CHANNELS_RGB32F:
	case TGFX_TEXTURE_CHANNELS_RGB32I:
	case TGFX_TEXTURE_CHANNELS_RGB32UI: return 12;
	case TGFX_TEXTURE_CHANNELS_RGBA32F:
	case TGFX_TEXTURE_CHANNELS_RGBA32I:
	case TGFX_TEXTURE_CHANNELS_RGBA32UI: return 16;
	default: return 0;
	}
}

TCORE_END_C_LINKAGE